# Data Store Configuration
DATA_STORE: ../data/assets.h5

# Target
TARGET_NAME: target_1

# Model Behavior
use_best_params: True
incremental_training: False
retrain_model: True
YEAR: 52
TARGET_THRESHOLD: 0
YEARS_TRAIN: 4
WEEKS_TEST: 1
WEEKS_VALIDATION: 2
CV_SPLITS: 10
CV_PURGE: 2
COVID_FILTER: true
USE_RETURN_AS_WEIGHT: false


# Model Fixed Parameters
model_params:
  objective: binary

  is_unbalance: true
  metric: average_precision_score
  boosting_type: gbdt
  extra_trees : true
  # use_quantized_grad: true
  # num_grad_quant_bins : 6

  verbose: -1

# Backtesting configuration
backtest_start_date: 2021-01-01

backtest_end_date: 2024-10-22 # Doesn't work if to_date is True
backtest_to_date: True
backtest_frequency: 1w


CATEGORICAL_FEATURES:
  - 'sector'
  - 'weekofyear'


ENABLE_OPTIMIZATION: true
OPTIMIZATION_TRIALS: 30


