# Data Store Configuration
DATA_STORE: ../data/assets.h5
DATA_CYCLES: ../data/cycles.h5

# General params
frequency: 'W'

# Recession cycles
rec_cycles:
  - date: "1980-01-01"
    phase: "recession"
  - date: "1980-07-01"
    phase: "expansion"

  - date: "1981-07-01"
    phase: "recession"
  - date: "1982-11-01"
    phase: "expansion"

  - date: "1990-07-01"
    phase: "recession"
  - date: "1991-03-01"
    phase: "expansion"

  - date: "2001-03-01"
    phase: "recession"
  - date: "2001-11-01"
    phase: "expansion"

  - date: "2007-12-01"
    phase: "recession"
  - date: "2009-06-01"
    phase: "expansion"

  - date: "2020-02-01"
    phase: "recession"
  - date: "2020-04-01"
    phase: "expansion"

fred_tickers:
  - GDPC1: "Real GDP, seasonally adjusted annual rate. Measures overall economic growth."
  - INDPRO: "Industrial Production Index. Reflects industrial activity and cyclical changes."
  - UNRATE: "Unemployment Rate. Countercyclical indicator for recessions and expansions."
  - CPIAUCSL: "Consumer Price Index for All Urban Consumers, seasonally adjusted. Evaluates price changes and inflation."
  - FEDFUNDS: "Federal Funds Rate. Associated with monetary policy and credit conditions."
  - GS10: "10-Year Treasury Constant Maturity Rate. Indicates inflation and growth expectations."
  - M2SL: "M2 Money Stock. Useful for analyzing changes in liquidity."
  - DSPIC96: "Real Disposable Personal Income, seasonally adjusted. Reflects households consumption capacity."