# Data Store Configuration
DATA_STORE: ../data/assets.h5

# Model Store
MODEL_RESULTS_PATH: ../model_results
lgbm_classification_model: tuning_lgb_classi_new.h5

# Parameters
YEAR: 52
TARGET_THRESHOLD: 0
YEARS_TRAIN: 3
WEEKS_TEST: 1
CV_SPLITS: 30
CV_PURGE: 3
delete_trained: True
VALIDATION_DATE: 2024-06-01

# Target
TARGET_NAME: return_1

COLUMNS_TO_KEEP:
  - 'sector'
  - 'weekofyear'


LAGS:  [1, 2, 3, 4, 8, 12, 26, 52]

ROLLING:
  - [12, 1, 'mean']
  - [12, 1, 'max']
  - [12, 1, 'std']
  - [12, 1, 'sum']
  - [12, 2, 'mean']
  - [26, 1, 'mean']
  - [26, 2, 'mean']
  - [52, 1, 'mean']
  - [52, 1, 'std']
  - [52, 2, 'mean']

MOMENTUM:
  - [2, 1, 1]
  - [3, 1, 1]
  - [4, 1, 1]
  - [12, 1, 1]
  - [12, 3, 1]

DIFF:
  - ['Mkt-RF', 1]
  - ['SMB', 1]
  - ['HML', 1]
  - ['RMW', 1]
  - ['CMA', 1]
  - ['lag_1', 1]
  - ['lag_52', 1]


TIME_FEATURES:
  month: 12
  weekofyear: 52

CATEGORICAL_FEATURES:
  - 'sector'

HYPERPARAMETER_SPACE:
  objective: [binary:logistic]
  eval_metric: [auc]
  booster: [gbtree]
  n_estimators: ['int', 100, 1000]
  alpha: ['loguniform', 0.00000001, 10.0]
  lambda: ['loguniform', 0.00000001, 10.0]
  max_depth: ['int', 3, 1000]
  learning_rate: ['loguniform', 0.001, 0.3]
  colsample_bytree: ['uniform', 0.6, 1.0]
  subsample: ['uniform', 0.6, 1.0]
  min_child_weight: ['int', 1, 20]
  verbose: [0]
