# Data Store Configuration
DATA_STORE: ../data/assets.h5

# Model Store
MODEL_RESULTS_PATH: ../model_results
lgbm_classification_model: tuning_lgb_classi_new.h5

# Parameters
YEAR: 52
TARGET_THRESHOLD: 0
YEARS_TRAIN: 4
WEEKS_TEST: 2
CV_SPLITS: 10
CV_PURGE: 2
delete_trained: True
VALIDATION_DATE: 2021-01-01
COVID_FILTER: True
USE_SELECTION_IF_AVAILABLE: false
KEEP_TIME_FEATURES: true
USE_RETURN_AS_WEIGHT: false

# Target
TARGET_NAME: target_1

COLUMNS_TO_KEEP:
  - 'sector'
  - 'weekofyear'
  - 'vix'
  - 'vixoil'
  - 'yield_curve'
  - 'corp_oas'
  - 'sentiment'
  - 'weekjobclaims'
  - 'inflation'
  - 'leading'


COLUMNS_TO_DROP:


FAMA_FRENCH_FACTORS:
  - Mkt-RF # Market Risk Premium: Market return minus risk-free rate.
  - SMB # Small Minus Big: Return spread between small and large-cap stocks.
  - HML # High Minus Low: Return spread between high and low book-to-market stocks.
  - RMW # Robust Minus Weak: Return spread between firms with robust and weak profitability.
  - CMA # Conservative Minus Aggressive: Return spread between firms with conservative and aggressive investment strategies.

LAGS:  [1, 2, 3, 4, 8, 12, 26, 52]

ROLLING:
  - [4, 1, 'mean']
  - [4, 1, 'max']
  - [12, 1, 'mean']
  - [12, 1, 'max']
  - [12, 1, 'std']
  - [12, 1, 'sum']
  - [12, 2, 'mean']

MOMENTUM:
  - [2, 1, 1]
  - [3, 1, 1]
  - [4, 1, 1]
  - [12, 1, 1]
  - [12, 3, 1]

DIFF:
  - ['Mkt-RF', 1]
  - ['SMB', 1]
  - ['HML', 1]
  - ['RMW', 1]
  - ['CMA', 1]
  - ['Mkt-RF', 52]
  - ['SMB', 52]
  - ['HML', 52]
  - ['RMW', 52]
  - ['CMA', 52]
  - ['lag_1', 1]
  - ['lag_1', 4]
  - ['lag_1', 8]
  - ['lag_1', 52]
  - ['lag_4', 1]
  - ['lag_4', 4]
  - ['lag_52', 1]


TIME_FEATURES:
  month: 12
  weekofyear: 52

CATEGORICAL_FEATURES:
  - 'sector'
  - 'weekofyear'

OPTIMIZATION_TRIALS: 30

